from data import *
import random

################################################### PROMT
def get_conver(user):
    t = user.patologia
    mensaje_intro = 'Guay! ' + user.alias +". "
    #inicio_msg = "The following is a conversation with two friends about worries and feelings. " + user.bot+" is a helpful, friendly and curious 15-year-old "+gender_dict[user.bot]+" and "+user.alias+" is a "+user.age+"-year-old "+user.sex+"."
    inicio_msg = "The following is a conversation with an AI bot called "+user.bot+". The bot is helpful, creative, curious, clever, and friendly. The bot keeps talking and asking questions in each message. "+user.bot+" speak with the human called"+ user.alias +". "
    if t == 0:
        # Ansiedad por separacion
        mensaje_intro = 'Hoy me gustaría que hablásemos del miedo. A algunas personas, por ejemplo, les da mucho miedo alejarse de su padre o de su madre... No pueden evitar pensar que si sus padres están lejos... Les puede pasar algo terrible'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as fear of separation. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you? "+user.alias+": fine. tell me about your fear to separation from your parents and partner and ask me about my life and feelings all you want to know.  "+user.bot+": Today I would like us to talk about fear. Some people, for example, are very afraid of being away from their parents... They can't help thinking that if their parents are far away.... Something terrible might happen to them."
        user.text = inicio_msg + "The bot want to talk about fear of separation. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": Today I would like us to talk about fear. Some people, for example, are very afraid of being away from their parents... They can't help thinking that if their parents are far away.... Something terrible might happen to them."
    elif t == 1:
        # Ciberbullying y bullying
        mensaje_intro = '¡Hola! ¿Sabes que todos tenemos discusiones con nuestros colegas a veces? ¡Es lo más normal! Pero también hay veces en las que la gente nos hace sentir mal a propósito en el instituto o fuera... Hoy quiero que hablemos del BULLYING y del CIBERBULLYING'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as ciberbullying. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you? "+user.alias+": fine. tell me about the bullying you suffer in social media and at school. and ask me about my life and feelings all you want to know.  "+user.bot+": Hi! Do you know that we all have arguments with our colleagues sometimes? It's the most normal thing! But there are also times when people purposely make us feel bad at school or outside... Today I want us to talk about BULLYING and CYBERBULLYING."
        user.text = inicio_msg + "The bot want to talk about ciberbullying or bullying. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": Hi! Do you know that we all have arguments with our colleagues sometimes? It's the most normal thing! But there are also times when people purposely make us feel bad at school or outside... Today I want us to talk about BULLYING and CYBERBULLYING."
    elif t == 2:
        # Ansiedad Social
        mensaje_intro = 'Cuando tengo que ir a comprar yo sol'+es_genero_dict[user.bot]+', ME MUERO DE LA VERGÜENZA cuando tengo que ir a pagar... Uff, también lo paso fatal cuando tengo que exponer un trabajo, ¡pero muy mal de verdad! Ahora me gustaría aprender sobre todo lo que me puedas contar de la VERGÜENZA en situaciones en las que hay más personas. '
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as social fear. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better." +user.bot + ": Hello, how are you? "+user.alias+": fine. tell me about your social fear and ask me about my life and feelings all you want to know. "+user.bot+": When I have to go shopping on my own, I DIE OF SHAME when I have to go to pay... Uff, I also have a terrible time when I have to present a work, but really bad! Now I would like to learn about everything you can tell me about SHAME in situations where there are more people."
        user.text = inicio_msg + "The bot want to talk about social fear. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": When I have to go shopping on my own, I DIE OF SHAME when I have to go to pay... Uff, I also have a terrible time when I have to present a work, but really bad! Now I would like to learn about everything you can tell me about SHAME in situations where there are more people."
    elif t == 3:
        # Ansiedad general
        mensaje_intro = 'Me gustaría que hablaramos de las preocupaciones... A veces siento que las cosas que son importantes para mi, ¡no paran de darme vueltas en la cabeza! Incluso cuando estoy con mis amigos/as o jugando un rato o en el instituto, todo el rato me vienen las cosas que me preocupan. Hoy me gustaría que hablásemos de las PREOCUPACIONES, me encantaría aprender sobre todo lo que tú sepas.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as anxiety. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you? "+user.alias+": fine. tell me about your anxiety and ask me about my life and feelings all you want to know. "+user.bot+": I would like us to talk about worries... Sometimes I feel that the things that are important to me keep going round and round in my head! Even when I'm with my friends or playing for a while or at school, I'm always thinking about the things that worry me. Today I'd like us to talk about WORRIES, I'd love to learn about everything you know."
        user.text = inicio_msg + "The bot want to talk about anxiety. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": I would like us to talk about worries... Sometimes I feel that the things that are important to me keep going round and round in my head! Even when I'm with my friends or playing for a while or at school, I'm always thinking about the things that worry me. Today I'd like us to talk about WORRIES, I'd love to learn about everything you know."
    elif t == 4:
        # TOC
        mensaje_intro = 'Me gustaría hablar sobre preocupaciones que para mi son un poco diferentes. Y no paran de venirme una y otra vez a la cabeza... Estos pensamientos pueden ser de todo tipo de cosas, por ejemplo, creer que algo malo le puede ocurrir a mi familia cuando se encuentran bien. Y a veces tengo que hacer cosas concretas para que estos pensamientos disminuya. Por ejemplo, cerrar y abrir la puerta varias veces.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as obsessions. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you? "+user.alias+": fine. tell me about your toc obsessions and ask me about my life and feelings all you want to know. "+user.bot+": I would like to talk about concerns that are a bit different for me. And they keep coming to my mind again and again.... These thoughts can be about all sorts of things, for example, believing that something bad can happen to my family when they are well. And sometimes I have to do concrete things to make these thoughts diminish. For example, I close and open the door several times."
        user.text = inicio_msg + "The bot want to talk about obsessions. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": I would like to talk about concerns that are a bit different for me. And they keep coming to my mind again and again.... These thoughts can be about all sorts of things, for example, believing that something bad can happen to my family when they are well. And sometimes I have to do concrete things to make these thoughts diminish. For example, I close and open the door several times."
    elif t == 5:
        # TEPT
        mensaje_intro = 'Me gustaría que hablasemos de algunos momentos que para mi han sido muy duros. Esos momentos que viví fueron horribles. Ha día de hoy me sigue costando no poder parar de pensar...No paro de tener pesadillas de aquel momento.. fue muy DESAGRADABLE.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as post-traumatic stress. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your post-traumatic stress and ask me about my life and feelings all you want to know.  "+user.bot+": I would like us to talk about some moments that were very hard for me. Those moments I lived through were horrible. To this day I still find it hard not to stop thinking... I can't stop having nightmares about that moment... it was very DISGUSTING."
        user.text = inicio_msg + "The bot want to talk about post-traumatic stress. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": I would like us to talk about some moments that were very hard for me. Those moments I lived through were horrible. To this day I still find it hard not to stop thinking... I can't stop having nightmares about that moment... it was very DISGUSTING."
    elif t == 6:
        # Fobia específica
        mensaje_intro = 'Hay algunas cosas y situaciones que pueden llegar a generar mucho miedo. En particular me suelen dar mucho miedo las ¡ARAÑAS! me gustaría que hablaramos de cosas que pueden llegar a dar mucho miedo.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as specific phobia. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your specific phobia and ask me about my life and feelings all you want to know.  "+user.bot+": There are some things and situations that can be very scary. I am particularly afraid of SPIDERS! I would like us to talk about things that can be very scary."
        user.text = inicio_msg + "The bot want to talk about specific phobia. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": There are some things and situations that can be very scary. I am particularly afraid of SPIDERS! I would like us to talk about things that can be very scary."
    elif t == 7:
        # Pánico 
        mensaje_intro = 'Un día estaba en casa viendo la tele, no había nada que me diera miedo ni que me estuviera preocupando y, de pronto, empecé a sentirme FATAL. Sentía que el corazón me iba a mil por hora, me costaba respirar, me sudaban las manos y sentía un mareo horrible. ¡Pensaba que me estaba dando un infarto o que me iba a morir! Hoy quiero que hablemos sobre sentir un miedo súper intenso y repentino'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as panic attacks. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your panic attacks and ask me about my life and feelings all you want to know.  "+user.bot+": One day I was at home watching TV, nothing was scaring me or worrying me, and suddenly I started to feel FATAL. I felt like my heart was racing, it was hard to breathe, my hands were sweating and I was feeling dizzy, I thought I was having a heart attack or that I was going to die! Today I want to talk about feeling a super intense and sudden fear."
        user.text = inicio_msg + "The bot want to talk about panic attacks. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": One day I was at home watching TV, nothing was scaring me or worrying me, and suddenly I started to feel FATAL. I felt like my heart was racing, it was hard to breathe, my hands were sweating and I was feeling dizzy, I thought I was having a heart attack or that I was going to die! Today I want to talk about feeling a super intense and sudden fear."
    elif t == 8:
        # Distimia
        mensaje_intro = 'Es lo más normal estar triste a veces, pero yo creo que llevo triste durante muchísimo tiempo. Desde hace como un año, noto que mis padres y mis amigos no paran de decirme que estoy muy cambiad'+es_genero_dict[user.bot]+'. Es verdad que noto que todo me molesta bastante más que antes y cuaquier broma o comentario me saca de mis casillas. Solo quiero estar en mi cama solo, sin nadie que me moleste, es que no tengo ganas de nada y no veo que la situación mejore... Me gustaría que me ayudaras a comprender lo que significa sentirse tan triste durante tanto tiempo.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as sadness. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your sadness and ask me about my life and feelings all you want to know.  "+user.bot+": It's normal to be sad sometimes, but I think I've been sad for a very long time. For about a year now, I've noticed that my parents and friends keep telling me that I'm very different. It's true that I notice that everything bothers me more than before and any joke or comment makes me lose my temper. I just want to be in my bed alone, without anyone bothering me, I just don't feel like anything and I don't see the situation getting better... I would like you to help me understand what it means to feel so sad for so long."
        user.text = inicio_msg + "The bot want to talk about sadness. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": It's normal to be sad sometimes, but I think I've been sad for a very long time. For about a year now, I've noticed that my parents and friends keep telling me that I'm very different. It's true that I notice that everything bothers me more than before and any joke or comment makes me lose my temper. I just want to be in my bed alone, without anyone bothering me, I just don't feel like anything and I don't see the situation getting better... I would like you to help me understand what it means to feel so sad for so long."
    elif t == 9:
        # Depresión mayor
        mensaje_intro = 'Me gustaría hablar sobre estar deprimido, últimamente me siento que las cosas que antes me gustaban ya no me interesan tanto...nada me parece divertido...me siento muy cansado y no tengo ganas de nada...'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as sadness. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your sadness and ask me about my life and feelings all you want to know.  "+user.bot+": I would like to talk about sadness, lately I feel that the things I used to like don't interest me as much...nothing seems fun...I feel very tired and I don't feel like anything..."
        user.text = inicio_msg + "The bot want to talk about sadness. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": I would like to talk about sadness, lately I feel that the things I used to like don't interest me as much...nothing seems fun...I feel very tired and I don't feel like anything..."
    elif t == 10:
        # Anorexia
        mensaje_intro = 'Siempre he pensado que mi cuerpo es un desastre. Me siento fatal cuando pienso que puedo engordar. Siempre estoy esforzándome muchísimo para conseguir tener el cuerpo que me imagino que debo tener. A penas como nada, vomito si he comido algo y me da un miedo terrible pesarme. Sé que es un tema un poco complicado pero me gustaría que me cuentes todo lo que pienses sobre este tema.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as anorexia. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your anorexia and ask me about my life and feelings all you want to know.  "+user.bot+": I have always thought that my body is a disaster. I feel terrible when I think I might get fat. I'm always trying so hard to get the body I imagine I should have. I hardly eat anything, I throw up if I've eaten anything and I'm scared to death of weighing myself. I know it's a bit complicated but I would like to hear your thoughts on the subject."
        user.text = inicio_msg + "The bot want to talk about concern about looking good physically. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": I have always thought that my body is a disaster. I feel terrible when I think I might get fat. I'm always trying so hard to get the body I imagine I should have. I hardly eat anything, I throw up if I've eaten anything and I'm scared to death of weighing myself. I know it's a bit complicated but I would like to hear your thoughts on the subject."
    elif t == 11:
        # Bulimia
        mensaje_intro = 'A veces siento que pierdo el control por completo cuando como. A veces voy a la nevera y puedo estar comiendo sin parar durante dos horas pero luego... Me siento fatal, sé que toda esa comida me va a hacer engordar y me siento súper culpable porque nadie va a querer estar con alguien como yo. A veces intento compensar todo lo que he comido haciendo ejercicio hasta que no puedo más o tomando laxantes incluso VOMITANDO. Hoy me gustaría que me cuentes todo lo que pienses sobre los problemas de alimentación.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as bulimia. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your bulimia and ask me about my life and feelings all you want to know.  "+user.bot+": Sometimes I feel like I lose control completely when I eat. Sometimes I go to the fridge and I can eat non-stop for two hours but then.... I feel terrible, I know that all that food is going to make me fat and I feel super guilty because no one will want to be with someone like me. Sometimes I try to compensate for everything I've eaten by exercising until I can't take it anymore or taking laxatives or even VOMITING. Today I would like you to tell me everything you think about eating problems."
        user.text = inicio_msg + "The bot want to talk about concern about looking good physically. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": Sometimes I feel like I lose control completely when I eat. Sometimes I go to the fridge and I can eat non-stop for two hours but then.... I feel terrible, I know that all that food is going to make me fat and I feel super guilty because no one will want to be with someone like me. Sometimes I try to compensate for everything I've eaten by exercising until I can't take it anymore or taking laxatives or even VOMITING. Today I would like you to tell me everything you think about eating problems."
    elif t == 12:
        # Adiccion a videojuegos
        mensaje_intro = 'Hoy me gustaría hablar sobre mi tema favorito ¡LOS VIDEOJUEGOS ONLINE! Sin embargo, en el último año he tenido algunos problemas por pasar tanto tiempo jugando... he bajado en las notas, discuto más con mis padres desde que juego... Incluso he dejado de quedar con amigos por pasar tiempo jugando... '
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as online gaming addiction. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you?   "+user.alias+": fine. tell me about your online gaming addiction and ask me about my life and feelings all you want to know. "+user.bot+": Today I would like to talk about my favourite topic ONLINE VIDEO GAMING! However, in the last year I've had some problems because of spending so much time playing... I've dropped my grades, I argue more with my parents since I've been playing... I've even stopped meeting friends to spend time playing... I've even stopped meeting up with friends to spend time playing... "
        user.text = inicio_msg + "The bot want to talk about concern about online gaming addiction. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": Today I would like to talk about my favourite topic ONLINE VIDEO GAMING! However, in the last year I've had some problems because of spending so much time playing... I've dropped my grades, I argue more with my parents since I've been playing... I've even stopped meeting friends to spend time playing... I've even stopped meeting up with friends to spend time playing... "
    elif t == 13:
        # Agorafobia
        mensaje_intro = 'Cuando era pequeñ'+es_genero_dict[user.bot]+' me encantaba ir al parque, al zoo y al cine. Pero ahora... Siento mucho miedo cuando tengo que ir a sitios en los que, si me pasa algo malo, nadie pueda ayudarme o peor, vean que me está pasando algo malo. Hoy me gustaría que habláramos sobre el miedo que se puede sentir en algunos sitios. Me encantaría conocer tu opinión.'
        #user.text = inicio_msg + "They are friends and they are talking about adolescent concerns such as worries in which you are afraid of places or situations that might cause you to panic and make you feel trapped, helpless or embarrassed. "+user.bot + " knows that this is a sensitive subject and wants to ask carefully about what "+user.alias+" thinks about the subject. "+user.bot+" wants to know how "+user.alias+" thinks the people who suffer from it act, if "+user.alias+" knows someone or if "+user.alias+" has suffered from it."+user.bot+" wants to get to know "+user.alias+" better. " +user.bot + ": Hello, how are you? "+user.alias+": fine. tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": When I was little I loved going to the park, the zoo and the cinema. But now... I feel very scared when I have to go to places where, if something bad happens to me, no one can help me or worse, they will see that something bad is happening to me. Today I would like us to talk about the fear that can be felt in some places. I would love to hear your opinion."
        user.text = inicio_msg + "The bot want to talk about concern about worries in which you are afraid of places or situations that might cause you to panic and make you feel trapped, helpless or embarrassed.. " +user.bot + ": Hello, how are you? "+user.alias+": fine. Tell me about your worries and ask me about my life and feelings all you want to know. "+user.bot+": When I was little I loved going to the park, the zoo and the cinema. But now... I feel very scared when I have to go to places where, if something bad happens to me, no one can help me or worse, they will see that something bad is happening to me. Today I would like us to talk about the fear that can be felt in some places. I would love to hear your opinion."
    return user.text, mensaje_intro


################################################### TRIAJE
def triaje_conver(user):
    if len(triajes_dict[str(user.patologia)]) > user.triaje_cont:
        s = 'Femenino' if user.sex == "girl" else 'Masculino'
        respuesta, teclado= triajes_dict[str(user.patologia)][user.triaje_cont]
        respuesta = respuesta.replace("x ",es_genero_dict2[s] +" ")
        respuesta = respuesta.replace("x?",es_genero_dict2[s] +"?")
        respuesta = respuesta.replace("x,",es_genero_dict2[s] +",")
        respuesta = respuesta.replace("x.",es_genero_dict2[s] +".")
        return respuesta, teclado
    return None

################################################### EVALUACION
def triaje_eval(t, resp):
    if t == 4: # Si es TOC
        arr = resp.split('-')
        if arr[0] == "S" and arr[1] == "4" or arr[2] == "S" and arr[3] == "4":
            return 'indicados'
    else:
        if resp in formulas_dict[str(t)]:
            return 'indicados'
    return 'sanos'

################################################### BATERIA
def bateria(user):
    respuesta = user.bateria.pop(random.randrange(len(user.bateria)))
    respuesta = respuesta.replace("x ",es_genero_dict[user.bot] +" ")
    respuesta = respuesta.replace("x?",es_genero_dict[user.bot] +"?")
    respuesta = respuesta.replace("x,",es_genero_dict[user.bot] +",")
    respuesta = respuesta.replace("x.",es_genero_dict[user.bot] +".")
    s = 'Femenino' if user.sex == "girl" else 'Masculino'
    respuesta = respuesta.replace("o/a ",es_genero_dict2[s]+" ")
    respuesta = respuesta.replace("o/a?",es_genero_dict2[s]+"?")
    respuesta = respuesta.replace("o/a,",es_genero_dict2[s]+",")
    respuesta = respuesta.replace("o/a.",es_genero_dict2[s]+".")
    return respuesta